# .travis.yml     Travis CI configuration file for MindForger
#
# Copyright (C) 2014-2020  Martin Dvorak <martin.dvorak@mindforger.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# For more details on Travis CI check:
#
# - https://travis-ci.org
# - https://docs.travis-ci.com/user/languages/cpp/
#
# Examples:
#
# - https://github.com/LunarG/VulkanSamples/blob/master/.travis.yml
#
# os:
#  - osx
# osx_image: xcode9.4
# eval "${MATRIX_EVAL}"
#

sudo: required
os:
  - linux
dist: bionic
  
language: cpp
compiler:
  - gcc
cache: ccache

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get update -qq
      "export DISPLAY=:99.0"
      "sh -e /etc/init.d/xvfb start"  
      sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
      sudo apt-get update -qq
    fi

install: # install dependencies & build Google Test Framework
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get install -qq qtbase5-dev libqt5webkit5-dev
      sudo apt-get install -qq qt5-default qttools5-dev-tools
      sudo apt-get install -qq ccache
      sudo apt-get install -qq libgtest-dev
      "export M8RHOME=`pwd`"
      cd /usr/src/gtest  # Google Test Framework
      sudo apt-get install -qq cmake
      sudo cmake .
      sudo make
      sudo mv libg* /usr/lib/
    fi

script: # make lib unit tests > run lib unit tests > make MF > install MF
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      cd "${M8RHOME}"
      cd deps/cmark-gfm && mkdir -v build && cd build && cmake -DCMARK_TESTS=OFF -DCMARK_SHARED=OFF .. && cmake --build . && cd ../../..
      "cd deps/discount && ./configure.sh && make ; cd ../.."
      "echo \"M8RDEBUG: g++ compiler is set to: ${CXX}\""  
      cd lib/test # UNIT tests
      qmake -r CONFIG+=mfnocxx CONFIG+=mfunits QMAKE_CXX=${CXX} mindforger-lib-unit-tests.pro
      make
      cd src && export M8R_GIT_PATH="${M8RHOME}" && ./mindforger-lib-unit-tests > /tmp/mindforger-unit-tests.log 2>&1 # ; true
      cd ../../..
      cat /tmp/mindforger-unit-tests.log
      #qmake -r CONFIG+=mfnocxx QMAKE_CXX=${CXX} mindforger.pro
      qmake -r CONFIG+=mfnocxx QMAKE_CXX=${CXX} mindforger.pro
      make
      sudo make install
    fi
