os:
  - linux
language: cpp
compiler:
  - g++
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install -qq g++-4.8; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - sudo apt-get install ccache
  - sudo apt-get install -qq qt52base qt52webkit qt52tools
script:
  - cd deps/discount && ./configure.sh && make ; cd ../..
  - qmake mindforger.pro
  - make
  - make check
  - sudo make install
