os:
  - linux
language: cpp # see https://docs.travis-ci.com/user/languages/cpp/
compiler:
  - gcc # Travis CI defines CXX=g++ env var
sudo: required
dist: trusty # Travis CI provides Precise and Trusty only

# solution to missing <codecvt>
script: 
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
  - gcc --version
  - bash build.sh
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

before_install:
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev libqt5webkit5-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
install:
  - sudo apt-get install -qq ccache
script:
  - cd deps/discount && ./configure.sh && make ; cd ../..
  - qmake mindforger.pro
  - make
  - make check
  - sudo make install
