os:
  - linux
  
# Missing codecvt: upgrade from g++ 4.8 to 5 > MATRIX_EVAL sets CXX to g++-5 > qmake CONFIG and QMAKE_CXX sets it to build process
matrix:
  include:
    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

language: cpp # see https://docs.travis-ci.com/user/languages/cpp/
compiler:
  - gcc # Travis CI defines CXX=g++ env var
sudo: required
dist: trusty # Travis CI provides Precise and Trusty only

before_install:
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"  
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install -qq qtbase5-dev libqt5webkit5-dev
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  - sudo apt-get install -qq ccache
  - sudo apt-get install -qq libgtest-dev

script: # make lib unit tests > run lib unit tests > make MF > install MF
  - eval "${MATRIX_EVAL}"
  - cd deps/discount && ./configure.sh && make ; cd ../..
  - "echo \"M8RDEBUG: g++ compiler is set to: ${CXX}\""  
  - cd lib/test # UNIT tests
  - qmake -r CONFIG+=travisci QMAKE_CXX=${CXX} mindforger-lib-unit-tests.pro
  - make
  - cd src && ./mindforger-lib-unit-tests && cd ../../..
  - qmake -r CONFIG+=travisci QMAKE_CXX=${CXX} mindforger.pro
  - make
  - sudo make install
