os:
  - linux
  
# 1/2 missing codecvt: upgrade from g++ 4.8 to 5
matrix:
  include:
    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

language: cpp # see https://docs.travis-ci.com/user/languages/cpp/
compiler:
  - gcc # Travis CI defines CXX=g++ env var
sudo: required
dist: trusty # Travis CI provides Precise and Trusty only
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev libqt5webkit5-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
install:
  - sudo apt-get install -qq ccache
script:
  - cd deps/discount && ./configure.sh && make ; cd ../..
  - qmake mindforger.pro
  - g++ --version # debug
  - g++-5 --version # debug
  - make CXX=q++-5 # 2/2 codecvt: ensure that non-default g++ is used
  - make check
  - sudo make install
